
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.gpteng.co https://cdnjs.cloudflare.com https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https://raw.githubusercontent.com; connect-src 'self' https://raw.githubusercontent.com https://unpkg.com https://cdnjs.cloudflare.com wss: ws:; worker-src 'self' blob: https://cdnjs.cloudflare.com https://unpkg.com; frame-src 'self' blob:; object-src 'none';"
    Access-Control-Allow-Origin = "*"
